package OmaMgpackage;

//import OmaMgpackage.JCDB;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author lentt
 */
public class MangaKirjasto extends javax.swing.JFrame {

    JCDB db = new JCDB();

    /**
     * Creates new form MangaKirjasto
     */
    public MangaKirjasto() throws ClassNotFoundException, SQLException {
        initComponents();

        tableloadMg(tbManga);
        comboloadMg(comboManga);
        tableloadKjs(tbKirjasto);
        comboload2(comboKirjasto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbKirjasto = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lblKjsRiviNro = new javax.swing.JLabel();
        btKjsTulosta = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbManga = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        lblMgRiviNro1 = new javax.swing.JLabel();
        btMgTulosta1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMgKustantaja = new javax.swing.JTextField();
        txtMgTekija = new javax.swing.JTextField();
        txtMgNimi = new javax.swing.JTextField();
        txtMgID = new javax.swing.JTextField();
        txtMgKieli = new javax.swing.JTextField();
        txtMgGenre = new javax.swing.JTextField();
        btMgLisaa = new javax.swing.JButton();
        btMgPaivita = new javax.swing.JButton();
        btMgPoista = new javax.swing.JButton();
        btValikkoTyhjenna = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtKjsHuom = new javax.swing.JTextField();
        txtKjsID = new javax.swing.JTextField();
        txtKjsNro = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        comboManga = new javax.swing.JComboBox<>();
        btKjsLisaa = new javax.swing.JButton();
        btKjsPaivita = new javax.swing.JButton();
        btKjsPoista = new javax.swing.JButton();
        comboKirjasto = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbKirjasto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nimi", "Tekijä", "Kustantaja", "Kieli", "Genre", "Nro.", "HUOM."
            }
        ));
        tbKirjasto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbKirjastoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbKirjasto);
        if (tbKirjasto.getColumnModel().getColumnCount() > 0) {
            tbKirjasto.getColumnModel().getColumn(0).setMaxWidth(50);
            tbKirjasto.getColumnModel().getColumn(6).setMaxWidth(70);
        }

        btKjsTulosta.setText("Tulosta");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btKjsTulosta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblKjsRiviNro, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btKjsTulosta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblKjsRiviNro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1122, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Kirjasto", jPanel5);

        tbManga.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nimi", "Tekijä", "Kustantaja", "Kieli", "Genre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbManga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMangaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbManga);
        if (tbManga.getColumnModel().getColumnCount() > 0) {
            tbManga.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        btMgTulosta1.setText("Tulosta");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btMgTulosta1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMgRiviNro1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btMgTulosta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMgRiviNro1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1122, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Manga", jPanel6);

        jLabel1.setText("Manga ID:");

        jLabel2.setText("Nimi:");

        jLabel3.setText("Tekijä:");

        jLabel4.setText("Kustantaja:");

        jLabel5.setText("Kieli:");

        jLabel6.setText("Genre:");

        txtMgID.setEditable(false);

        btMgLisaa.setText("Lisää");
        btMgLisaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMgLisaaActionPerformed(evt);
            }
        });

        btMgPaivita.setText("Päivitä");
        btMgPaivita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMgPaivitaActionPerformed(evt);
            }
        });

        btMgPoista.setText("Poista");
        btMgPoista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMgPoistaActionPerformed(evt);
            }
        });

        btValikkoTyhjenna.setText("Tyhjennä");
        btValikkoTyhjenna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btValikkoTyhjennaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btMgLisaa, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btMgPaivita)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btMgPoista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btValikkoTyhjenna))
                    .addComponent(txtMgID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMgKieli, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                    .addComponent(txtMgKustantaja, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                    .addComponent(txtMgTekija, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                    .addComponent(txtMgGenre, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                    .addComponent(txtMgNimi, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMgID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMgNimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMgTekija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMgKustantaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMgKieli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtMgGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btMgLisaa)
                    .addComponent(btMgPaivita)
                    .addComponent(btMgPoista)
                    .addComponent(btValikkoTyhjenna))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setText("Kirjasto ID:");

        jLabel8.setText("Nro.");

        jLabel9.setText("Huom.");

        txtKjsID.setEditable(false);

        jLabel10.setText("Mangan valinta:");

        comboManga.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                comboMangaPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        btKjsLisaa.setText("Lisää");
        btKjsLisaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKjsLisaaActionPerformed(evt);
            }
        });

        btKjsPaivita.setText("Päivitä");
        btKjsPaivita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKjsPaivitaActionPerformed(evt);
            }
        });

        btKjsPoista.setText("Poista");
        btKjsPoista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKjsPoistaActionPerformed(evt);
            }
        });

        comboKirjasto.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                comboKirjastoPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(comboKirjasto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtKjsID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtKjsNro, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtKjsHuom, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel9Layout.createSequentialGroup()
                                    .addComponent(btKjsLisaa)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btKjsPaivita)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btKjsPoista))))
                        .addGroup(jPanel9Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(comboManga, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtKjsID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(comboManga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtKjsNro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtKjsHuom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btKjsLisaa)
                    .addComponent(btKjsPaivita)
                    .addComponent(btKjsPoista))
                .addGap(18, 18, 18)
                .addComponent(comboKirjasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(246, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Valikko", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 511, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 779, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Haku", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane2)
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btValikkoTyhjennaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btValikkoTyhjennaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btValikkoTyhjennaActionPerformed

    private void btMgLisaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMgLisaaActionPerformed
        // Manga Lisää Nappi
        try {
            /**
             * Tarkistetaan ettei tekstikentät ole tyhjiä ja ettei ne ylitä
             * tiettyä merkki pituutta.
             */
            if (txtMgNimi.getText().isEmpty() || txtMgNimi.getText().length() > 50) {
                JOptionPane.showMessageDialog(null, "Nimi kenttä on tyhjä tai Nimi on yli 50 merkkiä pitkä!");

            } else if (txtMgTekija.getText().isEmpty() || txtMgTekija.getText().length() > 100) {
                JOptionPane.showMessageDialog(null, "Tekijä kenttä on tyhjä tai Tekijä on yli 100 merkkiä pitkä!");

            } else if (txtMgKustantaja.getText().isEmpty() || txtMgKustantaja.getText().length() > 50) {
                JOptionPane.showMessageDialog(null, "Kustantaja kenttä on tyhjä tai Kustantaja on yli 50 merkkiä pitkä!");

            } else if (txtMgKieli.getText().isEmpty() || txtMgKieli.getText().length() > 200) {
                JOptionPane.showMessageDialog(null, "Kieli kenttä on tyhjä tai Kieli on yli 20 merkkiä pitkä!");

            } else if (txtMgGenre.getText().isEmpty() || txtMgGenre.getText().length() > 50) {
                JOptionPane.showMessageDialog(null, "Genre kenttä on tyhjä tai Genre on yli 50 merkkiä pitkä!");

            } else {

                /**
                 * Kun on tarkistettu että teksti-kentissä on tekstiä niin
                 * haetaan ne ja tallennetaan tietokantaan. ID on
                 * automaattisesti generoitu
                 */
                db.putData("INSERT INTO MANGA(NIMI,TEKIJA,KUSTANTAJA,KIELI,GENRE) "
                        + "values('" + txtMgNimi.getText() + "','" + txtMgTekija.getText() + "','" + txtMgKustantaja.getText() + "','" + txtMgKieli.getText() + "','" + txtMgGenre.getText() + "')");

                /**
                 * Tyhjennetään tekstikentät ladataan uudestaan taulukot,
                 * valikot ja id:t-tekstikenttiin. Asetetaan Manga välilehti
                 * valituksi lasketaan raulukkojen rivit uudellen.
                 */
                tableloadMg(tbManga);
                comboloadMg(comboManga);

                tableloadKjs(tbKirjasto);
                comboload2(comboKirjasto);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(MangaKirjasto.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex);
        }


    }//GEN-LAST:event_btMgLisaaActionPerformed

    private void btMgPaivitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMgPaivitaActionPerformed
        try {
            //Tarkistetaan ettei tekstikentät ole tyhjiä. 
            if (txtMgNimi.getText().isEmpty() || txtMgNimi.getText().length() > 50) {
                JOptionPane.showMessageDialog(null, "Nimi kenttä on tyhjä tai Nimi on yli 50 merkkiä pitkä!");

            } else if (txtMgTekija.getText().isEmpty() || txtMgTekija.getText().length() > 100) {
                JOptionPane.showMessageDialog(null, "Tekijä kenttä on tyhjä tai Tekijä on yli 100 merkkiä pitkä!");

            } else if (txtMgKustantaja.getText().isEmpty() || txtMgKustantaja.getText().length() > 50) {
                JOptionPane.showMessageDialog(null, "Kustantaja kenttä on tyhjä tai Kustantaja on yli 50 merkkiä pitkä!");

            } else if (txtMgKieli.getText().isEmpty() || txtMgKieli.getText().length() > 200) {
                JOptionPane.showMessageDialog(null, "Kieli kenttä on tyhjä tai Kieli on yli 20 merkkiä pitkä!");

            } else if (txtMgGenre.getText().isEmpty() || txtMgGenre.getText().length() > 50) {
                JOptionPane.showMessageDialog(null, "Genre kenttä on tyhjä tai Genre on yli 50 merkkiä pitkä!");

            } else {
                /**
                 * Kun kaikissa kentissä on tietoa niin, haetaan päivitettävän
                 * tiedon id comboManga:sta ja muutetaan se int-muotoon
                 */
                String valinta = (String) comboManga.getSelectedItem();
                String[] nimet = valinta.split(" ");
                int mangaId = Integer.parseInt(nimet[0]);

                String nimi = txtMgNimi.getText();
                String tekija = txtMgTekija.getText();
                String kustantaja = txtMgKustantaja.getText();
                String kieli = txtMgKieli.getText();
                String genre = txtMgGenre.getText();

                //Haetaan tiedot tekstikentistä ja päivitetään tiedot tietokantaan
                db.putData("UPDATE MANGA SET NIMI  ='" + nimi + "', TEKIJA = '" + tekija + "', KUSTANTAJA ='" + kustantaja + "',  KIELI='" + kieli + "', GENRE ='" + genre + "'  WHERE ID = " + mangaId);

                /**
                 * Tyhjennetään tekstikentät ladataan uudestaan taulukot,
                 * valikot ja id:t-tekstikenttiin. Asetetaan Manga välilehti
                 * valituksi lasketaan raulukkojen rivit uudellen.
                 */
                tableloadMg(tbManga);
                comboloadMg(comboManga);

                tableloadKjs(tbKirjasto);
                comboload2(comboKirjasto);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MangaKirjasto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MangaKirjasto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btMgPaivitaActionPerformed

    private void btMgPoistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMgPoistaActionPerformed
        try {
            /**
             * Haetaan poistettavan tiedon id comboManga:sta ja muutetaan se
             * int-muotoon. Poistetaan tieto MANGA ja MGKIRJASTO:sta Manga ID:n
             * mukaan
             */
            String valinta = (String) comboManga.getSelectedItem();
            String[] nimet = valinta.split(" ");
            int mangaId = Integer.parseInt(nimet[0]);

            db.putData("DELETE FROM MANGA WHERE ID = " + mangaId);

            db.putData("DELETE FROM MGKIRJASTO WHERE ID_MANGA = " + mangaId);

            /**
             * Tyhjennetään tekstikentät ladataan uudestaan taulukot, valikot ja
             * id:t-tekstikenttiin. Asetetaan Manga välilehti valituksi
             * lasketaan raulukkojen rivit uudellen.
             */
            // clear();
            tableloadMg(tbManga);
            comboloadMg(comboManga);

            tableloadKjs(tbKirjasto);
            comboload2(comboKirjasto);
            /* idloadManga(txtMgID);

            
            idloadKirjasto(txtKjsID);
            jTabbedPane1.setSelectedIndex(1);
            rivinlasku();*/
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(MangaKirjasto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btMgPoistaActionPerformed

    private void tbMangaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMangaMouseClicked
        //Klikkaamalla taulukkossa jotakin tietoa ne päivittyvät tekstikenttiin
        //Valitun tiedon ID (paikka 0) lisätään Mangan nimi:-tekstikenttään
        txtMgID.setText(String.valueOf(tbManga.getValueAt(tbManga.getSelectedRow(), 0)));
        //Valitun tiedon nimi (paikka 1) lisätään Mangan nimi:-tekstikenttään
        txtMgNimi.setText(String.valueOf(tbManga.getValueAt(tbManga.getSelectedRow(), 1)));
        //Valitun tiedon tekijä (paikka 2) lisätään tekijä:-tekstikenttään
        txtMgTekija.setText(String.valueOf(tbManga.getValueAt(tbManga.getSelectedRow(), 2)));
        //Valitun tiedon kustantaja (paikka 3) lisätään kustantaja:-tekstikenttään
        txtMgKustantaja.setText(String.valueOf(tbManga.getValueAt(tbManga.getSelectedRow(), 3)));
        //Valitun tiedon kieli (paikka 4) lisätään kieli:-tekstikenttään
        txtMgKieli.setText(String.valueOf(tbManga.getValueAt(tbManga.getSelectedRow(), 4)));
        //Valitun tiedon Genre (paikka 5) lisätään Genre:-tekstikenttään
        txtMgGenre.setText(String.valueOf(tbManga.getValueAt(tbManga.getSelectedRow(), 5)));

        try {
            //Muutetaan taulukosta valitun rivin ID int-muotoon
            int valittuID = Integer.parseInt(String.valueOf(tbManga.getValueAt(tbManga.getSelectedRow(), 0)));

            //Haetaan tiedot tietokannasta
            ResultSet rset = db.getData("SELECT * FROM MANGA where ID= " + valittuID);

            //Valitaan valikosta taulukon valittu rivi
            while (rset.next()) {
                comboManga.setSelectedItem(rset.getInt("ID") + " " + rset.getString("NIMI") + " " + rset.getString("KIELI"));
            }
            //Tyhjennetään txtKjsNro tekstikenttä
            txtKjsNro.setText(null);
            txtKjsHuom.setText(null);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(MangaKirjasto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tbMangaMouseClicked

    private void comboMangaPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_comboMangaPopupMenuWillBecomeInvisible
        try {
            /**
             * Haetaan valittavan tiedon id comboManga:sta ja muutetaan se
             * int-muotoon. Haetaan tiedot tietokannasta. Lisätään ne
             * tekstikenttiin
             */
            String valinta = (String) comboManga.getSelectedItem();
            String[] nimet = valinta.split(" ");
            int mangaID = Integer.parseInt(nimet[0]);

            ResultSet rset;

            rset = db.getData("SELECT * FROM MANGA WHERE ID =" + mangaID);

            while (rset.next()) {

                txtMgID.setText(rset.getString("ID"));
                txtMgNimi.setText(rset.getString("NIMI"));
                txtMgTekija.setText(rset.getString("TEKIJA"));
                txtMgKustantaja.setText(rset.getString("KUSTANTAJA"));
                txtMgKieli.setText(rset.getString("KIELI"));
                txtMgGenre.setText(rset.getString("GENRE"));
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(MangaKirjasto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_comboMangaPopupMenuWillBecomeInvisible

    private void btKjsLisaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKjsLisaaActionPerformed
        try {
//Tarkistetaan ettei Nro tekstikenttä ole tyhjä

            if (txtKjsNro.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Nro kenttä ei saa olla tyhjä!");

            } else if (txtKjsHuom.getText().length() > 100) {
                JOptionPane.showMessageDialog(null, "Huom. kenttä on yli 100 merkkiä pitkä!");

            } else {
                /**
                 * Haetaan valittavan tiedon id comboManga:sta ja muutetaan se
                 * int-muotoon. Haetaan MANGA:n tiedot tietokannasta. Lisätään
                 * MGKIRJASTO:on mangan id ja Nro haetaan tekstikentästä
                 */
                String valinta = (String) comboManga.getSelectedItem();
                String[] nimet = valinta.split(" ");
                int mangaId = Integer.parseInt(nimet[0]);
                int nro = Integer.parseInt(txtKjsNro.getText());

                ResultSet rset = db.getData("SELECT * FROM MANGA WHERE ID = " + mangaId);

                while (rset.next()) {
                    db.putData("INSERT INTO MGKIRJASTO(ID_MANGA,NRO,HUOM) VALUES(" + rset.getInt("ID") + "," + nro + ",'" + txtKjsHuom.getText() + "')");
                }

                /**
                 * Tyhjennetään tekstikentät ladataan uudestaan taulukot,
                 * valikot ja id:t-tekstikenttiin. Asetetaan Manga välilehti
                 * valituksi lasketaan raulukkojen rivit uudellen.
                 */
                tableloadMg(tbManga);
                comboloadMg(comboManga);

                tableloadKjs(tbKirjasto);
                comboload2(comboKirjasto);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MangaKirjasto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MangaKirjasto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btKjsLisaaActionPerformed

    private void btKjsPaivitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKjsPaivitaActionPerformed
        
    }//GEN-LAST:event_btKjsPaivitaActionPerformed

    private void btKjsPoistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKjsPoistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btKjsPoistaActionPerformed

    private void tbKirjastoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbKirjastoMouseClicked
        //Klikkaamalla taulukkossa jotakin tietoa ne päivittyvät tekstikenttiin
        //Valitun tiedon id (paikka 0) lisätään KirjastoID:-tekstikenttään
        txtKjsID.setText(String.valueOf(tbKirjasto.getValueAt(tbKirjasto.getSelectedRow(), 0)));
        //Valitun tiedon nimi (paikka 1) lisätään Mangan nimi:-tekstikenttään
        txtMgNimi.setText(String.valueOf(tbKirjasto.getValueAt(tbKirjasto.getSelectedRow(), 1)));
        //Valitun tiedon tekijä (paikka 2) lisätään tekijä:-tekstikenttään
        txtMgTekija.setText(String.valueOf(tbKirjasto.getValueAt(tbKirjasto.getSelectedRow(), 2)));
        //Valitun tiedon kustantaja (paikka 3) lisätään kustantaja:-tekstikenttään
        txtMgKustantaja.setText(String.valueOf(tbKirjasto.getValueAt(tbKirjasto.getSelectedRow(), 3)));
        //Valitun tiedon kieli (paikka 4) lisätään kieli:-tekstikenttään
        txtMgKieli.setText(String.valueOf(tbKirjasto.getValueAt(tbKirjasto.getSelectedRow(), 4)));
        //Valitun tiedon genre (paikka 5) lisätään genre:-tekstikenttään
        txtMgGenre.setText(String.valueOf(tbKirjasto.getValueAt(tbKirjasto.getSelectedRow(), 5)));
        //Valitun tiedon nro (paikka 6) lisätään nro:-tekstikenttään
        txtKjsNro.setText(String.valueOf(tbKirjasto.getValueAt(tbKirjasto.getSelectedRow(), 6)));
        //Valitun tiedon huom (paikka 7) lisätään huom.:-tekstikenttään
        txtKjsHuom.setText(String.valueOf(tbKirjasto.getValueAt(tbKirjasto.getSelectedRow(), 7)));

        try {
            //Haetaan KirjastoID taulukosta ja muutetaan se int muotoon.
            int valittuKjsID = Integer.parseInt(String.valueOf(tbKirjasto.getValueAt(tbKirjasto.getSelectedRow(), 0)));
            //Haetaan tiedot comboManga-valikkoon

            ResultSet rset = db.getData("SELECT * FROM MGKIRJASTO INNER JOIN MANGA ON MGKIRJASTO.ID_MANGA = MANGA.ID WHERE KIRJASTOID= " + valittuKjsID);

            //Lisätään tiedot comboManga-valikkoon
            while (rset.next()) {
                System.out.println("lisätään comboon");
                 comboManga.setSelectedItem(rset.getInt("ID") + " " + rset.getString("NIMI") + " " + rset.getString("KIELI"));
                //Lisätään txtMgID-kenttään Manga ID 
                System.out.println("lisätty comboon");
                txtMgID.setText(rset.getString("ID"));
            }

            //Haetaan tiedot comboKirjasto-valikkoon
            ResultSet rset2 = db.getData("SELECT * FROM MGKIRJASTO INNER JOIN MANGA ON MGKIRJASTO.ID_MANGA = MANGA.ID WHERE KIRJASTOID= " + valittuKjsID);
            //Lisätään tiedot comboKirjasto-valikkoon
            while (rset2.next()) {
                System.out.println("lisätään comboon2");
                comboKirjasto.setSelectedItem(rset2.getInt("KIRJASTOID") + " " + rset2.getString("NIMI") + " " + rset2.getInt("NRO") + " " + rset2.getString("HUOM"));
                System.out.println("lisätty comboon2");
            }

            

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(MangaKirjasto.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex);
        }
    }//GEN-LAST:event_tbKirjastoMouseClicked

    private void comboKirjastoPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_comboKirjastoPopupMenuWillBecomeInvisible
        try {
            /**
             * Haetaan valittavan tiedon id comboKirjasto:sta ja muutetaan se
             * int-muotoon. Haetaan tiedot tietokannasta. Lisätään ne
             * tekstikenttiin
             */
            String valinta = (String) comboKirjasto.getSelectedItem();
            String[] nimet = valinta.split(" ");
            int kirjastoID = Integer.parseInt(nimet[0]);

            ResultSet rset;

            rset = db.getData("SELECT MGKIRJASTO.KIRJASTOID, MANGA.ID, MANGA.NIMI, MANGA.TEKIJA, MANGA.KUSTANTAJA, MANGA.KIELI, MANGA.GENRE, MGKIRJASTO.NRO, MGKIRJASTO.HUOM "
                    + "FROM MGKIRJASTO INNER JOIN MANGA ON MGKIRJASTO.ID_MANGA = MANGA.ID WHERE KIRJASTOID=" + kirjastoID);

            while (rset.next()) {

                txtMgID.setText(rset.getString("ID"));
                txtMgNimi.setText(rset.getString("NIMI"));
                txtMgTekija.setText(rset.getString("TEKIJA"));
                txtMgKustantaja.setText(rset.getString("KUSTANTAJA"));
                txtMgKieli.setText(rset.getString("KIELI"));
                txtMgGenre.setText(rset.getString("GENRE"));

                txtKjsID.setText(rset.getString("KIRJASTOID"));
                txtKjsNro.setText(rset.getString("NRO"));
                txtKjsHuom.setText(rset.getString("HUOM"));
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(MangaKirjasto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_comboKirjastoPopupMenuWillBecomeInvisible

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MangaKirjasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MangaKirjasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MangaKirjasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MangaKirjasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MangaKirjasto().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(MangaKirjasto.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(MangaKirjasto.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btKjsLisaa;
    private javax.swing.JButton btKjsPaivita;
    private javax.swing.JButton btKjsPoista;
    private javax.swing.JButton btKjsTulosta;
    private javax.swing.JButton btMgLisaa;
    private javax.swing.JButton btMgPaivita;
    private javax.swing.JButton btMgPoista;
    private javax.swing.JButton btMgTulosta1;
    private javax.swing.JButton btValikkoTyhjenna;
    private javax.swing.JComboBox<String> comboKirjasto;
    private javax.swing.JComboBox<String> comboManga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lblKjsRiviNro;
    private javax.swing.JLabel lblMgRiviNro1;
    private javax.swing.JTable tbKirjasto;
    private javax.swing.JTable tbManga;
    private javax.swing.JTextField txtKjsHuom;
    private javax.swing.JTextField txtKjsID;
    private javax.swing.JTextField txtKjsNro;
    private javax.swing.JTextField txtMgGenre;
    private javax.swing.JTextField txtMgID;
    private javax.swing.JTextField txtMgKieli;
    private javax.swing.JTextField txtMgKustantaja;
    private javax.swing.JTextField txtMgNimi;
    private javax.swing.JTextField txtMgTekija;
    // End of variables declaration//GEN-END:variables

//MANGA
    private void tableloadMg(JTable jt) throws ClassNotFoundException, SQLException {
        //Luodaan taulukko malli
        DefaultTableModel dt = (DefaultTableModel) jt.getModel();
        //Asetetaan rivit aloittamaan 0
        dt.setRowCount(0);
        //Luodaan taulukko lajittelija ja asetetaan se manga taulukkoon
        TableRowSorter<TableModel> sorter;
        sorter = new TableRowSorter<TableModel>(dt);
        tbManga.setRowSorter(sorter);
        //Haetaan tiedot tietokannasta ja lisätään ne taulukkoon
        ResultSet rset = db.getData("SELECT * FROM MANGA");

        while (rset.next()) {
            Vector v = new Vector();
            v.add(rset.getString(1));
            v.add(rset.getString(2));
            v.add(rset.getString(3));
            v.add(rset.getString(4));
            v.add(rset.getString(5));
            v.add(rset.getString(6));
            dt.addRow(v);
        }
    }

    private void comboloadMg(JComboBox jl) throws ClassNotFoundException, SQLException {
        //Alustetaan comboManga
        comboManga.removeAllItems();
        //Haetaan tiedot tietokannasta ja lisätään ne valintaComboon. 
        ResultSet rset = db.getData("SELECT * FROM MANGA");
        while (rset.next()) {
            String pat = rset.getInt("ID") + " " + rset.getString("NIMI") + " " + rset.getString("KIELI");
            comboManga.addItem(pat);
        }
    }

    //MGKIRJASTO
    private void tableloadKjs(JTable jt2) throws ClassNotFoundException, SQLException {
        //Luodaan taulukko malli
        DefaultTableModel dt = (DefaultTableModel) jt2.getModel();
        //Asetetaan rivit aloittamaan 0
        dt.setRowCount(0);
        //Luodaan taulukko lajittelija ja asetetaan se kirjasto taulukkoon
        TableRowSorter<TableModel> sorter;
        sorter = new TableRowSorter<TableModel>(dt);
        tbKirjasto.setRowSorter(sorter);

        //Haetaan tiedot tietokannasta ja lisätään ne taulukkoon
        ResultSet rset = db.getData("SELECT MGKIRJASTO.KIRJASTOID, MANGA.NIMI, MANGA.TEKIJA, MANGA.KUSTANTAJA, MANGA.KIELI, MANGA.GENRE, MGKIRJASTO.NRO, MGKIRJASTO.HUOM "
                + "FROM MGKIRJASTO INNER JOIN MANGA ON MGKIRJASTO.ID_MANGA = MANGA.ID");

        while (rset.next()) {
            Vector v = new Vector();
            v.add(rset.getString(1));
            v.add(rset.getString(2));
            v.add(rset.getString(3));
            v.add(rset.getString(4));
            v.add(rset.getString(5));
            v.add(rset.getString(6));
            v.add(rset.getString(7));
            v.add(rset.getString(8));

            dt.addRow(v);
        }
    }

    private void comboload2(JComboBox jl2) throws ClassNotFoundException, SQLException {
        //Alustetaan comboKirjasto
        comboKirjasto.removeAllItems();
        //Haetaan tiedot tietokannasta ja lisätään ne valintaComboon. 
        ResultSet rset = db.getData("SELECT * FROM MGKIRJASTO INNER JOIN MANGA ON MGKIRJASTO.ID_MANGA = MANGA.ID");
        while (rset.next()) {
            String pat = rset.getInt("KIRJASTOID") + " " + rset.getString("NIMI") + " " + rset.getInt("NRO") + " " + rset.getString("HUOM");
            comboKirjasto.addItem(pat);
        }
    }

}
